[package]
name = "cv_rtsp_video_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
opencv = "0.84.5"
rayon = "1.8.0"
tokio = { version = "1.32.0", features = ["full"] }
